services:
  mysql:
    image: mysql:8.0
    container_name: projet-bdd-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: boutique_pc
      MYSQL_USER: UTILISATEUR
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always
